### ISSUE TITLE
Save

### ISSUE THREAD

**Issue by SpyridoulaZagkou4** [madsendennis/notebooks#2]
Hi! How can we save predicted mask to a nifti format?

**Comment by madsendennis** [comment]
Hi. Have a look at the nibabel getting started page: https://nipy.org/nibabel/gettingstarted.html

And remember to apply the original image transformation to your prediction. So something like: 
import nibabel as nib
img = nib.load('your_input_img_to_be_segmented.nii')
segmentedImage = UNET(img) # segment the image using unet - output is then the segmented volume
outvol = nib.Nifti1Image(segmentedImage, img.affine, img.header) # use the header and affine from the original image
nib.save(outvol, 'your_segmented_img.nii')

**Comment by SpyridoulaZagkou4** [comment]
yeah thank you , i have an error when i try to print affine for predicted mask ---> 'numpy.ndarray' object has no attribute 'affine'. In your code you use  dataobj_images.DataobjImage to recognizepredicted mask. Can I use the same instructions for this type?

**Comment by madsendennis** [comment]
That is just to convert it into the datatype that the nifty widget uses. 
The predicted mask has no affine attribute as it is a numpy array. You need to apply the same transformation to your prediction as was in the original .nii image that you wanted to segment. 
If following the code, this is saved in: imgTargetNii = nib.load(targetImagePath)
so the imgTargetNii.affine and imgTargetNii.header should contain the info that you want to apply to your predicted mask as well. 
You can also just use: nib.Nifti1Image(segmentedImage), but the location of the segmentation might be different than the imgTargetNii.
